### ISSUE TITLE
object has no attribute maxhours_average_consumption_this_month

### ISSUE THREAD

**Issue by pittbull** [uphillbattle/NettleieElvia#7]
Getting error "AttributeError: 'NettleieElvia' object has no attribute 'maxhours_average_consumption_this_month'" on your latest code.

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/1532149/193407278-28838fc8-cc41-443f-a8cc-23bd7200d692.png">

**Comment by uphillbattle** [comment]
Yep, I noticed that as well. The problem, I believe, is that at the beginning of the month, the average peak consumption is not available. Since it is the peak hour of three different days, one must apparently, and probably, have completed at least one day before the value is available.

As a quick fix, I set the value to 0 as a default value in case no value is available from the API. See   [v0.5.1](https://github.com/uphillbattle/NettleieElvia/releases/tag/v0.5.1).
